# Generated by Django 3.0.7 on 2022-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('realtors', '0001_initial'),
	]
	
	operations = [
		migrations.AlterField(
			model_name='realtor',
			name='photo',
			field=models.FileField(upload_to='photos/%Y/%m/%d/'),
		),
	]
